version: '3.9'

services:
  vue-app:
    build: ./frontend
    image: #change to my frontend image
    ports:
      # Nginx container listen on port 80
      # Access the frontend by http://localhost:8080 
      - "80:80"  
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend-app
    networks:
      - intranet

  backend-app:
    build: ./backend
    image: #change to my backend image 
    expose:
      - "8000"
    restart: always
    networks:
      - intranet

networks:
  intranet:

volumes:
  mariadb_data:
